[Interface]
PrivateKey = {{ .PrivateKey }}
Address = {{ .Address }}
DNS = {{ range $i, $dns := .DNS }}{{ if $i }}, {{ end }}{{ $dns }}{{ end }}

[Peer]
PublicKey = {{ .ServerPublicKey }}
Endpoint = {{ .Endpoint }}:{{ .Port }}
AllowedIPs = {{ range $i, $ip := .AllowedIPs }}{{ if $i }}, {{ end }}{{ $ip }}{{ end }}
PersistentKeepalive = {{ .PersistentKeepalive }}
