[Interface]
PrivateKey = {{ .PrivateKey }}
Address = {{ .Address }}
ListenPort = {{ .ListenPort }}
PostUp = iptables -t nat -A POSTROUTING -s {{ .Subnet }} -o {{ .ExternalIface }} -j MASQUERADE
PostUp = iptables -A FORWARD -i %i -o {{ .ExternalIface }} -j ACCEPT
PostUp = iptables -A FORWARD -i {{ .ExternalIface }} -o %i -m state --state RELATED,ESTABLISHED -j ACCEPT
{{ range .DisabledPeerIPs }}
PostUp = iptables -I FORWARD 1 -i %i -s {{ . }} -j DROP
PostDown = iptables -D FORWARD -i %i -s {{ . }} -j DROP
{{ end }}
PostDown = iptables -t nat -D POSTROUTING -s {{ .Subnet }} -o {{ .ExternalIface }} -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -o {{ .ExternalIface }} -j ACCEPT
PostDown = iptables -D FORWARD -i {{ .ExternalIface }} -o %i -m state --state RELATED,ESTABLISHED -j ACCEPT
{{ range .Peers }}
[Peer]
PublicKey = {{ .PublicKey }}
AllowedIPs = {{ .AllowedIPs }}
{{ end }}